[package]
name = "min-writing"
version = "0.1.0"
entrypoint = "src/lib.typ"
authors = ["Maycon F. Melo <@mayconfmelo>"]
license = "MIT-0"
description = "Simple and basic general purpose writings"
categories = [ "layout", "office" ]
keywords = [ "quick writing", "note", "anotation", "mobile" ]
repository = "https://github.com/mayconfmelo/min-writing"
exclude = [
  "dev/",
  "test/",
  "docs/",
  "scripts/",
  ".git",
  ".todo",
  ".gitignore",
  "justfile",
  "CHANGELOG.md",
  "SETUP.md",
  "manual.typ"
path = "template"
]


[template]
entrypoint = "main.typ"
thumbnail = "thumbnail.png"
